M48
; DRILL file {KiCad (7.0.0)} date Tue Apr 25 22:11:27 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-25T22:11:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X102.87Y-48.26
X102.87Y-137.16
X191.77Y-48.26
X191.77Y-137.16
T0
M30
