M48
; DRILL file {KiCad (7.0.0)} date Thu Jul  6 21:55:19 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-06T21:55:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X104.902Y-47.244
X104.902Y-136.144
X193.802Y-47.244
X193.802Y-136.144
T0
M30
