M48
; DRILL file {KiCad (7.0.0)} date Tue Apr 25 22:37:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-25T22:37:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.03Y-50.8
X113.03Y-139.7
X201.93Y-50.8
X201.93Y-139.7
T0
M30
